### ISSUE TITLE
Not working with Python3.5 ---> ImportError: No module named 'Conversion'

### ISSUE THREAD

**Issue by lwgray** [lwgray/pyEntrezId#6]
After successful 'Pip install PyEntrezId' into anaconda python3.5 environment, if I try to import PyEntrezId into Ipython session, I get the following error:
## In [1]: from PyEntrezId import Conversion

ImportError                               Traceback (most recent call last)
<ipython-input-1-f98e9271de3c> in <module>()
----> 1 from PyEntrezId import Conversion

/home/lwgray/Entrez/PyEntrezId/**init**.py in <module>()
----> 1 from Conversion import Conversion

ImportError: No module named 'Conversion'

**Comment by hichamjanati** [comment]
Change the __init__ file line: 
 from Conversion import Conversion 
to:
from .Conversion import Conversion
